---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Safe Settings Sync

on:
  push:
    branches: ["main"]
    paths:
      - .github/settings.yml
      - .github/workflows/safe-settings-sync.yaml
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=github/safe-settings
      SAFE_SETTINGS_VERSION: 2.1.16
      SAFE_SETTINGS_CODE_DIR: ${{ github.workspace }}/.safe-settings-code
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Checkout Safe Settings
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: github/safe-settings
          ref: $SAFE_SETTINGS_VERSION
          path: $SAFE_SETTINGS_CODE_DIR

      - name: Setup Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0

      - name: Install Dependencies
        run: npm install
        working-directory: $SAFE_SETTINGS_CODE_DIR

      - name: Run Sync
        run: npm run full-sync
        working-directory: $SAFE_SETTINGS_CODE_DIR
        env:
          GH_ORG: ${{ github.repository_owner }}
          APP_ID: ${{ secrets.BOT_APP_ID }}
          PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          ADMIN_REPO: .github
